### PR TITLE
Update `ecmaVersion` to 2020 to support optional chaining operator.

### PR DESCRIPTION
**Pull request by kaibolay**
This fixes a lint problem introduced by #943.

```
$ npm run lint
[...]
firebase/functions-samples/authenticated-json-api/functions/index.js
  95:33  error  Parsing error: Unexpected token .
```

### CODE REVIEW

**Comment by kaibolay** [comment]
FYI: The CI tests fail with
```
Error: delete-unused-accounts-cron/functions compile: index.js(33,27): error TS2351: This expression is not constructable.
delete-unused-accounts-cron/functions compile:   Type 'typeof import("/home/runner/work/functions-samples/functions-samples/node_modules/.pnpm/es6-promise-pool@2.5.0/node_modules/es6-promise-pool/es6-promise-pool")' has no construct signatures.
delete-unused-accounts-cron/functions compile: Failed
```

That is caused by #996 - if I revert that compiling works.

**Review by jhuleatt — APPROVED** [review]
